### ISSUE TITLE
Stream API

### ISSUE THREAD

**Issue by coldhiber** [lddubeau/saxes#15]
First of all thank a lot for the cool library!

In @exceljs we are going to get rid of old sax parser and replace it to the saxes lib. But there is a problem that the saxes doesn't provide the native streaming API. Looks like it was removed from the original sources.

Since the exceljs is highly coupled to the streaming API, we are looking for ways how can we add this API to the saxes.

Do you think is it possible to do this for the reasonable effort? Or maybe it's possible to avoid this at all.

**Comment by lddubeau** [comment]
Right. The streaming API was not preserved when I forked. The implementation of the streaming API in sax did not keep up with the recommendations as to how to implement streams. I had no need for the streaming API myself so it was difficult to justify spending the time to bring it up to date. (Conversely, it was very urgent for me to release saxes.) And it wasn't clear whether it was actually being used by anyone.

> Or maybe it's possible to avoid this at all.

I'm not sure what you mean. Do you mean whether you can do what you need to do without using a streaming API. I'd expect you can. With a streaming API, you'd do:

```
const readable = getReadableStreamSomehow();
readable.pipe(streamingParser);
```

You can replace that with a loop. Using the [example provided with Node's documentation](https://nodejs.org/api/stream.html#stream_readable_read_size) and replacing the `console.log` with `parser.write`, you'd have something like this:

```
const readable = getReadableStreamSomehow();
readable.on('readable', () => {
  let chunk;
  while (null !== (chunk = readable.read())) {
    parser.write(chunk);
  }
});
```

`parser` is just the regular parser provided by saxes.

**Comment by coldhiber** [comment]
@lddubeau got it. Thanks a lot for the details! I think firstly we'll try to avoid using Stream API. Maybe we'll add a sort of wrapper or something like that.
