### ISSUE TITLE
Normalization of end-of-line characters

### ISSUE THREAD

**Issue by DrRataplan** [lddubeau/saxes#2]
When I run the following in a browser:
`JSON.stringify(new DOMParser().parseFromString('<p>A\r\nB</p>', 'text/xml').documentElement.textContent)`. It returns the following string: `"A\nB"`

However, in saxes, I get an ontext event with `A\r\nB` as the text argument.

[The spec](https://www.w3.org/TR/xml/#sec-line-ends) states that it is the responsibility of the 'XML processor' to normalize line endings. Since saxes is an XML parser, I'd say that saxes should normalize these line endings.

What's your opinion on this matter?

**Comment by lddubeau** [comment]
I'm thinking you're right again. Thank you for the report! This is going to complicate the parsing logic a bit because saxes allows streaming so it is not possible when encountering `\r` at the end of a chunk of data to know how it should be handled until the next chunk comes.

**Comment by lddubeau** [comment]
The new release has a fix for this an your other report.

**Comment by DrRataplan** [comment]
Wow, cool!

Thanks a lot for your quick response!
