### ISSUE TITLE
Whitespace characters in attribute values are not normalized

### ISSUE THREAD

**Issue by bwrrp** [lddubeau/saxes#24]
I have an XML document containing an attribute with carriage return characters: (https://github.com/w3c/xsdtests/blob/master/msData/regex/RegexTest_63.xml)

If I read the XML spec correctly regarding attribute value normalization (https://www.w3.org/TR/xml/#AVNormalize), I think these should be normalized to a single space character. However, the following test case shows that this does not currently happen:

```
const p = new saxes.SaxesParser();
p.onopentag = n => console.log(JSON.stringify(n.attributes['att']));
p.write('<doc att="a\rb"/>').close();
// logs "a\rb"
```

**Comment by lddubeau** [comment]
I've just pushed out rc4 which contains a fix. It would be good if you could try it. (rc3 was a misfire... :frowning_face: )

**Comment by bwrrp** [comment]
That was fast! I can confirm that each \r has now been turned into a space. The XML file linked in the original issue does not contain a doctype, which is probably why these three spaces are not further combined into one, so this seems to be working as expected. Thanks!
