### ISSUE TITLE
Disallowed character

### ISSUE THREAD

**Issue by Christilut** [lddubeau/saxes#26]
Hi,

I'm getting the error `disallowed character` when an attribute value has the character `Ë`.
For example:
```
<NODE Name="TËST"/>
```

For now I'm just ignoring the error and parsing continues correctly.

**Comment by lddubeau** [comment]
I've plopped your example into a file, parsed it with the latest version of saxes, and did not get the error you are reporting. Can you submit a complete example (code and data) that reproduces the error you got?

**Comment by Christilut** [comment]
Thanks for the quick reply. Your answer made me look twice to how I supplied the data and turns out I was mangling unicode characters right before feeding it into the writer. Now it works fine, thanks :)
