### ISSUE TITLE
White space following XML declaration should be part of the prolog

### ISSUE THREAD

**Issue by Zirro** [lddubeau/saxes#3]
The [ProcessingInstruction-literal-1.xhtml](https://github.com/web-platform-tests/wpt/blob/master/dom/nodes/ProcessingInstruction-literal-1.xhtml) test currently fails in jsdom, as `document.firstChild` returns a text node instead of the first element. The test does pass in browsers.

I have tracked this down to the newline that follows the XML declaration. If I've understood the [relevant part of the specification](https://www.w3.org/TR/2008/REC-xml-20081126/#xmldoc) correctly, then comments, processing instructions and white space directly after the XML declaration should be seen as part of the prolog and not result in an event.

**Comment by lddubeau** [comment]
The specification does not explicitly mandate what parsers show to client code using them.

For instance, [sax](https://github.com/isaacs/sax-js) would simply not emit events for empty comments or empty CDATA sections. There's nothing in the XML specification that mandates that a parser show to the client code empty comments or empty CDATA sections. So there was no argument there that sax was wrong with regards to the XML specification. The argument one have been one of utility: some use-case scenarios (e.g. parsing XML for creating a DOM tree) require knowing about such empty structures, and sax cannot be used for such scenarios. 

The same applies to whitespace outside the root node. A parser can decide to not tell the client code about such spaces, whereas another parser may tell the client code. The XML specification does not tell one way or another. Saxes does tell the client about spaces outside the root node, and the client may choose to ignore them.

The solution here is to modify jsdom's parsing code to ignore text nodes that appear outside the root node of a document. I can make the change there. Is there a specific branch I should work on?

**Comment by Zirro** [comment]
Ah, from the code in jsdom I had been under the impression that data about the prolog was intentionally discarded by sax(es) as I saw no events resulting from the XML declaration. I see now that there is a separate `xmlDecl` property for this information.

Your offer to fix it in jsdom is appreciated. There's no particular branch for this, as I'm just looking into the causes of long-standing issues one by one. Thanks!
