### ISSUE TITLE
Can saxes be used with asynchronous callbacks?

### ISSUE THREAD

**Issue by pkruk2** [lddubeau/saxes#45]
Hi,

is it possible to use await in event callbacks? Something like `saxParser.on("opentag", async (node) => { await ...` ?

It looks like it's not possible, but would like to confirm...

**Comment by dobromyslov** [comment]
Same question. Is it possible to process events asynchronously with nested async/await? Is it possible to stop events emitting if asynchronous processing of previous events is not complete?

**Comment by dobromyslov** [comment]
@pkruk2 have a look at this solution: https://github.com/lddubeau/saxes/issues/32#issuecomment-640493042

**Comment by lddubeau** [comment]
@dobromyslov  You'd have to do something like you suggest in the comment. Sorry for the long delay in responding. I'm having some health concerns (not covid-19 related).

I'm going to close this. You can continue commenting if needed.
